apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/sleepr-450316/notifications/production
        name: notifications
        env:
        - name: PORT
          value: '3000'
        - name: GOOGLE_OAUTH_CLIENT_ID
          value: 34544592006-2tcasls09ju2rh67pj73hgbpbocddosf.apps.googleusercontent.com
        - name: SMTP_USER
          value: kevinkhoa0203@gmail.com
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google
              key: clientSecret
        - name: GOOGLE_OAUTH_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: google
              key: refreshToken
        - name: GOOGLE_OAUTH_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: google
              key: accessToken
        
        ports:
          - containerPort: 3000